In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["harry","rohan","skillf","shubh"],
    "marks":[91,67,87,33],
    "city":['belagavi','hassan','dharward','bangalore']

}

In [3]:
df=pd.DataFrame(dict1)

In [4]:
df

     name  marks       city
0   harry     91   belagavi
1   rohan     67     hassan
2  skillf     87   dharward
3   shubh     33  bangalore

In [5]:
# df.to_csv("")

In [7]:
#  df.tp_csv("",index==flase)
# is r0,,1,2,3emoved #
# index by the function index==flase

In [8]:
#df.head() function show data from strating
# df.tail() function show data from the bottom

In [9]:
#df.describe
# it do the statistcal analysis like maximum value minimum value like etc
# it also provide the mean value as well

In [10]:
# pd.read_csv(copy path)
# it read the csv and convert it into dataframe

In [11]:
# filename[column name][index number]=changing to new value at index 0

In [12]:
# file name.index=[first , second, third, fourth..]
# numbers changed to word like 1 to one it means
# the index numberical number changed to alphabetical number

##what is pandas ?

 #pandas is an open source data analysis libray written in python

#pandas has 2 types of data structure

series and dataframe
series :- 1d array(labled)capable of holding any type of data series

dataframe= 2d array(labled) structure with columns of potenitally different types of data

In [15]:
# example for seeries
ser=pd.Series(np.random.rand(34))

In [14]:
type(ser)

pandas.core.series.Series

In [16]:
#  example for data frame
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [17]:
newdf

            0         1         2         3         4
0    0.598862  0.090831  0.615410  0.628312  0.695309
1    0.224786  0.738287  0.299411  0.956378  0.132882
2    0.369976  0.068997  0.757729  0.695593  0.412915
3    0.837472  0.508638  0.301441  0.454255  0.330876
4    0.144332  0.224760  0.269934  0.077901  0.864873
..        ...       ...       ...       ...       ...
329  0.150809  0.554750  0.455593  0.032511  0.251377
330  0.425633  0.935585  0.326888  0.474547  0.444967
331  0.036647  0.440348  0.233983  0.990904  0.118205
332  0.045288  0.656242  0.439913  0.369612  0.173081
333  0.756062  0.092617  0.158228  0.525195  0.653368

[334 rows x 5 columns]

In [18]:
type(newdf)

pandas.core.frame.DataFrame

In [19]:
newdf.index  #index funvtion gives the index length of the file

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [20]:
newdf.columns # columns fnction gives the number of columns in it

RangeIndex(start=0, stop=5, step=1)

In [21]:
newdf.to_numpy # converts pandas to numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0    0.598862  0.090831  0.615410  0.628312  0.695309
1    0.224786  0.738287  0.299411  0.956378  0.132882
2    0.369976  0.068997  0.757729  0.695593  0.412915
3    0.837472  0.508638  0.301441  0.454255  0.330876
4    0.144332  0.224760  0.269934  0.077901  0.864873
..        ...       ...       ...       ...       ...
329  0.150809  0.554750  0.455593  0.032511  0.251377
330  0.425633  0.935585  0.326888  0.474547  0.444967
331  0.036647  0.440348  0.233983  0.990904  0.118205
332  0.045288  0.656242  0.439913  0.369612  0.173081
333  0.756062  0.092617  0.158228  0.525195  0.653368

[334 rows x 5 columns]>

In [22]:
newdf.T# it transposde it meaning rows beaome column and column become rows by using T function in pandas

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.598862,0.224786,0.369976,0.837472,0.144332,0.811563,0.884233,0.607137,0.814474,0.259679,...,0.153810,0.810413,0.678764,0.959355,0.939011,0.150809,0.425633,0.036647,0.045288,0.756062
1,0.090831,0.738287,0.068997,0.508638,0.224760,0.004036,0.443132,0.594625,0.227741,0.832001,...,0.799531,0.653488,0.716085,0.797979,0.467023,0.554750,0.935585,0.440348,0.656242,0.092617
2,0.615410,0.299411,0.757729,0.301441,0.269934,0.030801,0.692910,0.459669,0.942910,0.758540,...,0.417087,0.128573,0.895938,0.604619,0.635042,0.455593,0.326888,0.233983,0.439913,0.158228
3,0.628312,0.956378,0.695593,0.454255,0.077901,0.558598,0.689996,0.233571,0.922352,0.149744,...,0.835558,0.566161,0.254982,0.559564,0.322666,0.032511,0.474547,0.990904,0.369612,0.525195
4,0.695309,0.132882,0.412915,0.330876,0.864873,0.662493,0.555200,0.916360,0.644370,0.773348,...,0.106196,0.205862,0.347474,0.333847,0.969577,0.251377,0.444967,0.118205,0.173081,0.653368

In [25]:
newdf.head()

          0         1         2         3         4
0  0.598862  0.090831  0.615410  0.628312  0.695309
1  0.224786  0.738287  0.299411  0.956378  0.132882
2  0.369976  0.068997  0.757729  0.695593  0.412915
3  0.837472  0.508638  0.301441  0.454255  0.330876
4  0.144332  0.224760  0.269934  0.077901  0.864873

In [26]:
newdf.sort_index(axis=0,ascending=False)# it prints in reverseway
# axis =0 ,means sort in only rows

            0         1         2         3         4
333  0.756062  0.092617  0.158228  0.525195  0.653368
332  0.045288  0.656242  0.439913  0.369612  0.173081
331  0.036647  0.440348  0.233983  0.990904  0.118205
330  0.425633  0.935585  0.326888  0.474547  0.444967
329  0.150809  0.554750  0.455593  0.032511  0.251377
..        ...       ...       ...       ...       ...
4    0.144332  0.224760  0.269934  0.077901  0.864873
3    0.837472  0.508638  0.301441  0.454255  0.330876
2    0.369976  0.068997  0.757729  0.695593  0.412915
1    0.224786  0.738287  0.299411  0.956378  0.132882
0    0.598862  0.090831  0.615410  0.628312  0.695309

[334 rows x 5 columns]

In [27]:
newdf.sort_index(axis=1,ascending=False)
## axis =1 ,means sort in only columns

            4         3         2         1         0
0    0.695309  0.628312  0.615410  0.090831  0.598862
1    0.132882  0.956378  0.299411  0.738287  0.224786
2    0.412915  0.695593  0.757729  0.068997  0.369976
3    0.330876  0.454255  0.301441  0.508638  0.837472
4    0.864873  0.077901  0.269934  0.224760  0.144332
..        ...       ...       ...       ...       ...
329  0.251377  0.032511  0.455593  0.554750  0.150809
330  0.444967  0.474547  0.326888  0.935585  0.425633
331  0.118205  0.990904  0.233983  0.440348  0.036647
332  0.173081  0.369612  0.439913  0.656242  0.045288
333  0.653368  0.525195  0.158228  0.092617  0.756062

[334 rows x 5 columns]

# combination data series is data frame

In [28]:
newdf[0] # taking the 1st row and column from data frame

0      0.598862
1      0.224786
2      0.369976
3      0.837472
4      0.144332
         ...
329    0.150809
330    0.425633
331    0.036647
332    0.045288
333    0.756062
Name: 0, Length: 334, dtype: float64

In [30]:
type(newdf[0])

pandas.core.series.Series